{{- if $.Values.eck_agent.enabled -}}
{{- include "elasticagent.preset.init" $ -}}
{{- range $presetName, $presetVal := $.Values.eck_agent.presets -}}
{{- $agentName := printf "agent-%s" (lower $presetName) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $agentName }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
    {{- with ($presetVal).labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($presetVal).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ $agentName }}
    namespace: {{ $.Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ $agentName }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}