{{- if $.Values.eck_agent.enabled -}}
{{- include "elasticagent.preset.init" $ -}}
{{- range $presetName, $presetVal := $.Values.eck_agent.presets -}}
{{- $agentName := printf "agent-%s" (lower $presetName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $agentName }}
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
    {{- with ($presetVal).labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($presetVal).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{ end }}
{{ end }}